=== jbosstools/jbosstools-jst/plugins/org.jboss.tools.jst.web.kb/resources/kbCustomTagLibSchema-1.0.dtd
<!--
<!DOCTYPE tag-lib PUBLIC "-//Red Hat, Inc//DTD Knowledge Base 2.0//EN" "http://anonsvn.jboss.org/repos/jbosstools/trunk/jst/plugins/org.jboss.tools.jst.web.kb/resources/kbCustomTagLibSchema-1.0.dtd">
-->

<!ENTITY % Boolean "(true|false)">

<!--
	tag-lib is a root element. May contain component
	Attributes:
	dafault-prefix - Default prefix.
	ignoreCase - "true" - Ignore case of letters in name of attributes and components
-->
<!ELEMENT tag-lib (component*, component-extension?)>

<!ATTLIST tag-lib dafaultPrefix CDATA #IMPLIED>
<!ATTLIST tag-lib ignoreCase %Boolean; #IMPLIED>

<!--
	component describes a component.
	component can contain attributes.
	Attributes:
	name - name of component
	closeTag - "true" - Component cannot have a body.
	           "false" - Component can have a body. Used by default.
	extended - "true" - Component is relevant only if this component exists in other tag-libs (tld, faclets, ...). Set to "true" by default.
-->
<!ELEMENT component (description?, component*, attribute*)>

<!ATTLIST component name CDATA #REQUIRED>
<!ATTLIST component closeTag %Boolean; #IMPLIED>
<!ATTLIST component extended %Boolean; #IMPLIED>

<!--
	Describes attribute of component.
	Attributes:
	name - Name of attribute type.
        dataProvider - If name is not defined then dataProvider is responsible to provide the list of attributes for this component.
	required - "true" - attribute of element is required. "false" by default.
	defaultValue - default value of attribute.
	extended - "true" - Attribute is relevant only if this attribute exists in other tag-libs (tld, faclets, ...). Set to "true" by default.
-->
<!ELEMENT attribute (description?, proposal*)>

<!ATTLIST attribute name CDATA #IMPLIED>
<!ATTLIST attribute dataProvider CDATA #IMPLIED>
<!ATTLIST attribute required %Boolean; #REQUIRED>
<!ATTLIST attribute defaultValue CDATA #IMPLIED>
<!ATTLIST attribute extended %Boolean; #IMPLIED>

<!--
	Describe content assist proposal for value of attribute.
	Attributes:
	type - Type of proposal.
-->
<!ELEMENT proposal (param*)>

<!ATTLIST proposal type CDATA #REQUIRED>

<!--
	Describes parameter of proposal.
	Attributes:
	value - Value of param.
	name - Name of param.
-->
<!ELEMENT param ()>

<!ATTLIST param value CDATA #REQUIRED>
<!ATTLIST param name CDATA #IMPLIED>

<!ELEMENT description ()>

<!--
	component extension describes common attributes with additional meta information
	for component attributes in case these attributes are present in other types of tag libs.
	For example this element could add proposals for every "rendered" attributes for any tag lib.
-->
<!ELEMENT component-extension (attribute*) >

=== jbosstools/jbosstools-jst/plugins/org.jboss.tools.jst.web.kb/taglibs/AngularJS.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE tag-lib PUBLIC "-//Red Hat, Inc//DTD Knowledge Base 2.0//EN" "http://anonsvn.jboss.org/repos/jbosstools/trunk/jst/plugins/org.jboss.tools.jst.web.kb/resources/kbCustomTagLibSchema-1.0.dtd">
<tag-lib defaultPrefix="angularJS" ignoreCase="true">
	<component-extension>
		<attribute name="ng-click" extended="false"/>
		<attribute name="data-ng-click" extended="false"/>
		<attribute name="ng-bind" extended="false">
		</attribute>
		<attribute name="data-ng-bind" extended="false">
		</attribute>
		<attribute name="ng-bind-html" extended="false">
		</attribute>
		<attribute name="data-ng-bind-html" extended="false">
		</attribute>
		<attribute name="ng-bind-template" extended="false">
		</attribute>
		<attribute name="data-ng-bind-template" extended="false">
		</attribute>
		<attribute name="ng-class" extended="false">
		</attribute>
		<attribute name="data-ng-class" extended="false">
		</attribute>
		<attribute name="ng-class-even" extended="false">
		</attribute>
		<attribute name="data-ng-class-even" extended="false">
		</attribute>
		<attribute name="ng-class-odd" extended="false">
		</attribute>
		<attribute name="data-ng-class-odd" extended="false">
		</attribute>
		<attribute name="ng-cloak" extended="false">
		</attribute>
		<attribute name="data-ng-cloak" extended="false">
		</attribute>
		<attribute name="ng-controller" extended="false">
		</attribute>
		<attribute name="data-ng-controller" extended="false">
		</attribute>
		<attribute name="ng-dblclick" extended="false">
		</attribute>
		<attribute name="data-ng-dblclick" extended="false">
		</attribute>
		<attribute name="ng-form" extended="false">
		</attribute>
		<attribute name="data-ng-form" extended="false">
		</attribute>
		<attribute name="ng-hide" extended="false">
		</attribute>
		<attribute name="data-ng-hide" extended="false">
		</attribute>
		<attribute name="ng-if" extended="false">
		</attribute>
		<attribute name="data-ng-if" extended="false">
		</attribute>
		<attribute name="ng-include" extended="false">
		</attribute>
		<attribute name="data-ng-include" extended="false">
		</attribute>
		<attribute name="ng-init" extended="false">
		</attribute>
		<attribute name="data-ng-init" extended="false">
		</attribute>
		<attribute name="ng-keydown" extended="false">
		</attribute>
		<attribute name="data-ng-keydown" extended="false">
		</attribute>
		<attribute name="ng-keypress" extended="false">
		</attribute>
		<attribute name="data-ng-keypress" extended="false">
		</attribute>
		<attribute name="ng-keyup" extended="false">
		</attribute>
		<attribute name="data-ng-keyup" extended="false">
		</attribute>
		<attribute name="ng-mousedown" extended="false">
		</attribute>
		<attribute name="data-ng-mousedown" extended="false">
		</attribute>
		<attribute name="ng-mouseenter" extended="false">
		</attribute>
		<attribute name="data-ng-mouseenter" extended="false">
		</attribute>
		<attribute name="ng-mouseleave" extended="false">
		</attribute>
		<attribute name="data-ng-mouseleave" extended="false">
		</attribute>
		<attribute name="ng-mousemove" extended="false">
		</attribute>
		<attribute name="data-ng-mousemove" extended="false">
		</attribute>
		<attribute name="ng-mouseover" extended="false">
		</attribute>
		<attribute name="data-ng-mouseover" extended="false">
		</attribute>
		<attribute name="ng-mouseup" extended="false">
		</attribute>
		<attribute name="data-ng-mouseup" extended="false">
		</attribute>
		<attribute name="ng-non-bindable" extended="false">
		</attribute>
		<attribute name="data-ng-non-bindable" extended="false">
		</attribute>
		<attribute name="ng-repeat" extended="false">
		</attribute>
		<attribute name="data-ng-repeat" extended="false">
		</attribute>
		<attribute name="ng-repeat-start" extended="false"/>
		<attribute name="data-ng-repeat-start" extended="false"/>
		<attribute name="ng-repeat-end" extended="false"/>
		<attribute name="data-ng-repeat-end" extended="false"/>
		<attribute name="ng-selected" extended="false">
		</attribute>
		<attribute name="data-ng-selected" extended="false">
		</attribute>
		<attribute name="ng-show" extended="false">
		</attribute>
		<attribute name="data-ng-show" extended="false">
		</attribute>
		<attribute name="ng-style" extended="false">
		</attribute>
		<attribute name="data-ng-style" extended="false">
		</attribute>
		<attribute name="ng-transclude" extended="false">
		</attribute>
		<attribute name="data-ng-transclude" extended="false">
		</attribute>
	</component-extension>
	<component-extension attributeProvider="org.jboss.tools.jst.web.kb.internal.taglib.html.angular.NgAppAttributeProvider"/>
	<component-extension attributeProvider="org.jboss.tools.jst.web.kb.internal.taglib.html.angular.NgClassAttributeProvider"/>
	<component-extension attributeProvider="org.jboss.tools.jst.web.kb.internal.taglib.html.angular.NameAttributeProvider"/>
	<component-extension attributeProvider="org.jboss.tools.jst.web.kb.internal.taglib.html.angular.NgPluralizeAttributeProvider"/>
	<component-extension attributeProvider="org.jboss.tools.jst.web.kb.internal.taglib.html.angular.NgSwitchAttributeProvider"/>

	<component extended="false" name="html">
		<attribute name="ng-csp" extended="false">
		</attribute>
		<attribute name="data-ng-csp" extended="false">
		</attribute>
	</component>
	<component extended="false" name="details">
		<attribute name="ng-open" extended="false">
		</attribute>
		<attribute name="data-ng-open" extended="false">
		</attribute>
	</component>
	<component name="script" extended="false">
		<attribute name="type" extended="false">
			<proposal type="enumeration">
				<param value="text/ng-template" />
			</proposal>
		</attribute>
	</component>

    <component extended="false" name="form" attributeProvider="org.jboss.tools.jst.web.kb.internal.taglib.html.angular.NgSubmitAttributeProvider"/>
	<component extended="false" name="input" attributeProvider="org.jboss.tools.jst.web.kb.internal.taglib.html.angular.NgModelAttributeProvider,org.jboss.tools.jst.web.kb.internal.taglib.html.angular.NgDisabledAttributeProvider,org.jboss.tools.jst.web.kb.internal.taglib.html.angular.NgAnyInputAttributeProvider, org.jboss.tools.jst.web.kb.internal.taglib.html.angular.NgBlurAttributeProvider, org.jboss.tools.jst.web.kb.internal.taglib.html.angular.NgInputAttributeProvider, org.jboss.tools.jst.web.kb.internal.taglib.html.angular.NgInputCheckboxAttributeProvider, org.jboss.tools.jst.web.kb.internal.taglib.html.angular.NgInputDefaultAttributeProvider, org.jboss.tools.jst.web.kb.internal.taglib.html.angular.NgInputRadioAttributeProvider, org.jboss.tools.jst.web.kb.internal.taglib.html.angular.NgInputTextAttributeProvider"/>
	<component extended="false" name="window" attributeProvider="org.jboss.tools.jst.web.kb.internal.taglib.html.angular.NgBlurAttributeProvider"/>
	<component extended="false" name="select" attributeProvider="org.jboss.tools.jst.web.kb.internal.taglib.html.angular.NgSelectAttributeProvider,org.jboss.tools.jst.web.kb.internal.taglib.html.angular.NgModelAttributeProvider,org.jboss.tools.jst.web.kb.internal.taglib.html.angular.NgBlurAttributeProvider"/>
	<component extended="false" name="textarea" attributeProvider="org.jboss.tools.jst.web.kb.internal.taglib.html.angular.NgTextareaAttributeProvider,org.jboss.tools.jst.web.kb.internal.taglib.html.angular.NgModelAttributeProvider,org.jboss.tools.jst.web.kb.internal.taglib.html.angular.NgBlurAttributeProvider"/>
	<component extended="false" name="a" attributeProvider="org.jboss.tools.jst.web.kb.internal.taglib.html.angular.NgLinkAttributeProvider,org.jboss.tools.jst.web.kb.internal.taglib.html.angular.NgBlurAttributeProvider"/>
	<component extended="false" name="button" attributeProvider="org.jboss.tools.jst.web.kb.internal.taglib.html.angular.NgDisabledAttributeProvider"/>
	<component extended="false" name="img" attributeProvider="org.jboss.tools.jst.web.kb.internal.taglib.html.angular.NgImageAttributeProvider"/>
	
</tag-lib>

=== jbosstools/jbosstools-jst/plugins/org.jboss.tools.jst.web.kb/taglibs/JsfCore.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE tag-lib PUBLIC "-//Red Hat, Inc//DTD Knowledge Base 2.0//EN" "http://anonsvn.jboss.org/repos/jbosstools/trunk/jst/plugins/org.jboss.tools.jst.web.kb/resources/kbCustomTagLibSchema-1.0.dtd">
<tag-lib defaultPrefix="f">

	<component closeTag="true" name="facet">
        <attribute name="name">
            <proposal type="facetName"/>
        </attribute>
	</component>

	<component closeTag="true" name="loadBundle">
        <attribute name="basename">
            <proposal type="bundleName"/>
        </attribute>
	</component>

	<component closeTag="true" name="convertDateTime">
		<attribute name="dateStyle">
			<proposal type="enumeration">
				<param value="default" />
				<param value="short" />
				<param value="medium" />
				<param value="long" />
				<param value="full" />
			</proposal>
		</attribute>
		<attribute name="timeStyle">
			<proposal type="enumeration">
				<param value="default" />
				<param value="short" />
				<param value="medium" />
				<param value="long" />
				<param value="full" />
			</proposal>
		</attribute>
		<attribute name="type">
			<proposal type="enumeration">
				<param value="date" />
				<param value="time" />
				<param value="both" />
			</proposal>
		</attribute>
	</component>
	<component closeTag="true" name="convertNumber">
		<attribute name="groupingUsed">
			<proposal type="enumeration">
				<param value="true" />
				<param value="false" />
			</proposal>
		</attribute>
		<attribute name="integerOnly">
			<proposal type="enumeration">
				<param value="true" />
				<param value="false" />
			</proposal>
		</attribute>
		<attribute name="type">
			<proposal type="enumeration">
				<param value="number" />
				<param value="currency" />
				<param value="percentage" />
			</proposal>
		</attribute>
	</component>

	<component closeTag="true" name="selectItem">
		<attribute name="itemDisabled">
			<proposal type="enumeration">
				<param value="true" />
				<param value="false" />
			</proposal>
		</attribute>
	</component>
</tag-lib>

=== jbosstools/jbosstools-jst/plugins/org.jboss.tools.jst.web.kb/taglibs/JsfHtmlBasic.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE tag-lib PUBLIC "-//Red Hat, Inc//DTD Knowledge Base 2.0//EN" "http://anonsvn.jboss.org/repos/jbosstools/trunk/jst/plugins/org.jboss.tools.jst.web.kb/resources/kbCustomTagLibSchema-1.0.dtd">
<tag-lib defaultPrefix="h">
	<component closeTag="true" name="commandButton">
		<attribute name="action" required="true" />
		<attribute name="value" required="true" />
		<attribute name="image">
			<proposal type="file">
				<param name="extensions" value="%image%" />
				<param name="pathType" value="absolute" />
				<!-- param name="pathAddition"
					value="#{facesContext.externalContext.requestContextPath}" / -->
			</proposal>
		</attribute>
		<attribute name="type">
			<proposal type="enumeration">
				<param value="submit" />
				<param value="reset" />
			</proposal>
		</attribute>
	</component>

	<component closeTag="true" name="commandLink">
		<attribute name="action" required="true" />
		<attribute name="value" required="true" />
		<attribute name="shape">
			<proposal type="enumeration">
				<param value="default" />
				<param value="rect" />
				<param value="circle" />
				<param value="poly" />
			</proposal>
		</attribute>
	</component>

	<component name="dataTable">
		<attribute name="frame">
			<proposal type="enumeration">
				<param value="none" />
				<param value="above" />
				<param value="below" />
				<param value="hsides" />
				<param value="vsides" />
				<param value="lhs" />
				<param value="rhs" />
				<param value="box" />
				<param value="border" />
			</proposal>
		</attribute>
		<attribute name="rules">
			<proposal type="enumeration">
				<param value="none" />
				<param value="groups" />
				<param value="rows" />
				<param value="cols" />
				<param value="all" />
			</proposal>
		</attribute>
	</component>

	<component closeTag="true" name="graphicImage">
		<attribute name="url">
			<proposal type="file">
				<param name="extensions" value="%image%" />
			</proposal>
		</attribute>
		<attribute name="value" required="true">
			<proposal type="file">
				<param name="extensions" value="%image%" />
			</proposal>
		</attribute>
		<attribute name="ismap">
			<proposal type="enumeration">
				<param value="true" />
				<param value="false" />
			</proposal>
		</attribute>
	</component>

	<component closeTag="true" name="inputHidden">
		<attribute name="value" required="true" />
	</component>

	<component closeTag="true" name="inputSecret">
		<attribute name="value" required="true" />
		<attribute name="redisplay">
			<proposal type="enumeration">
				<param value="true" />
				<param value="false" />
			</proposal>
		</attribute>
	</component>

	<component closeTag="true" name="inputText">
		<attribute name="value" required="true" />
	</component>

	<component closeTag="true" name="inputTextarea">
		<attribute name="value" required="true" />
	</component>

	<component closeTag="true" name="message">
		<attribute name="showDetail">
			<proposal type="enumeration">
				<param value="true" />
				<param value="false" />
			</proposal>
		</attribute>
		<attribute name="showSummary">
			<proposal type="enumeration">
				<param value="true" />
				<param value="false" />
			</proposal>
		</attribute>
		<attribute name="tooltip">
			<proposal type="enumeration">
				<param value="true" />
				<param value="false" />
			</proposal>
		</attribute>
	</component>

	<component closeTag="true" name="messages">
		<attribute name="globalOnly">
			<proposal type="enumeration">
				<param value="true" />
				<param value="false" />
			</proposal>
		</attribute>
		<attribute name="showDetail">
			<proposal type="enumeration">
				<param value="true" />
				<param value="false" />
			</proposal>
		</attribute>
		<attribute name="showSummary">
			<proposal type="enumeration">
				<param value="true" />
				<param value="false" />
			</proposal>
		</attribute>
		<attribute name="tooltip">
			<proposal type="enumeration">
				<param value="true" />
				<param value="false" />
			</proposal>
		</attribute>
		<attribute name="layout">
			<proposal type="enumeration">
				<param value="horizontal" />
				<param value="vertical" />
			</proposal>
		</attribute>
	</component>

	<component closeTag="true" name="outputFormat">
		<attribute name="value" required="true" />
	</component>

	<component closeTag="true" name="outputLabel">
		<attribute name="value" required="true" />
	</component>

	<component name="outputLink">
		<attribute name="shape">
			<proposal type="enumeration">
				<param value="default" />
				<param value="rect" />
				<param value="circle" />
				<param value="poly" />
			</proposal>
		</attribute>
	</component>

	<component closeTag="true" name="outputText">
		<attribute name="value" required="true" />
	</component>

	<component name="panelGrid">
		<attribute name="frame">
			<proposal type="enumeration">
				<param value="none" />
				<param value="above" />
				<param value="below" />
				<param value="hsides" />
				<param value="vsides" />
				<param value="lhs" />
				<param value="rhs" />
				<param value="box" />
				<param value="border" />
			</proposal>
		</attribute>
		<attribute name="rules">
			<proposal type="enumeration">
				<param value="none" />
				<param value="groups" />
				<param value="rows" />
				<param value="cols" />
				<param value="all" />
			</proposal>
		</attribute>
	</component>

	<component name="panelGroup">
		<attribute name="layout">
			<proposal type="enumeration">
				<param value="block" />
			</proposal>
		</attribute>
	</component>

	<component closeTag="true" name="selectBooleanCheckbox">
		<attribute name="value" required="true" />
	</component>

	<component name="selectManyCheckbox">
		<attribute name="value" required="true" />
		<attribute name="layout">
			<proposal type="enumeration">
				<param value="pageDirection" />
				<param value="lineDirection" />
			</proposal>
		</attribute>
	</component>

	<component name="selectManyListbox">
		<attribute name="value" required="true" />
	</component>

	<component name="selectManyMenu">
		<attribute name="value" required="true" />
	</component>

	<component name="selectOneListbox">
		<attribute name="value" required="true" />
	</component>

	<component name="selectOneMenu">
		<attribute name="value" required="true" />
	</component>

	<component name="selectOneRadio">
		<attribute name="value" required="true" />
		<attribute name="layout">
			<proposal type="enumeration">
				<param value="pageDirection" />
				<param value="lineDirection" />
			</proposal>
		</attribute>
	</component>
</tag-lib>
