=== jbosstools/jbosstools-jst/plugins/org.jboss.tools.jst.web.kb/resources/kbCustomTagLibSchema-1.0.dtd
<!--
<!DOCTYPE tag-lib PUBLIC "-//Red Hat, Inc//DTD Knowledge Base 2.0//EN" "http://anonsvn.jboss.org/repos/jbosstools/trunk/jst/plugins/org.jboss.tools.jst.web.kb/resources/kbCustomTagLibSchema-1.0.dtd">
-->

<!ENTITY % Boolean "(true|false)">

<!--
	tag-lib is a root element. May contain component
	Attributes:
	dafault-prefix - Default prefix.
	ignoreCase - "true" - Ignore case of letters in name of attributes and components
-->
<!ELEMENT tag-lib (component*, component-extension?)>

<!ATTLIST tag-lib dafaultPrefix CDATA #IMPLIED>
<!ATTLIST tag-lib ignoreCase %Boolean; #IMPLIED>

<!--
	component describes a component.
	component can contain attributes.
	Attributes:
	name - name of component
	closeTag - "true" - Component cannot have a body.
	           "false" - Component can have a body. Used by default.
	extended - "true" - Component is relevant only if this component exists in other tag-libs (tld, faclets, ...). Set to "true" by default.
-->
<!ELEMENT component (description?, component*, attribute*)>

<!ATTLIST component name CDATA #REQUIRED>
<!ATTLIST component closeTag %Boolean; #IMPLIED>
<!ATTLIST component extended %Boolean; #IMPLIED>

<!--
	Describes attribute of component.
	Attributes:
	name - Name of attribute type.
        dataProvider - If name is not defined then dataProvider is responsible to provide the list of attributes for this component.
	required - "true" - attribute of element is required. "false" by default.
	defaultValue - default value of attribute.
	extended - "true" - Attribute is relevant only if this attribute exists in other tag-libs (tld, faclets, ...). Set to "true" by default.
-->
<!ELEMENT attribute (description?, proposal*)>

<!ATTLIST attribute name CDATA #IMPLIED>
<!ATTLIST attribute dataProvider CDATA #IMPLIED>
<!ATTLIST attribute required %Boolean; #REQUIRED>
<!ATTLIST attribute defaultValue CDATA #IMPLIED>
<!ATTLIST attribute extended %Boolean; #IMPLIED>

<!--
	Describe content assist proposal for value of attribute.
	Attributes:
	type - Type of proposal.
-->
<!ELEMENT proposal (param*)>

<!ATTLIST proposal type CDATA #REQUIRED>

<!--
	Describes parameter of proposal.
	Attributes:
	value - Value of param.
	name - Name of param.
-->
<!ELEMENT param ()>

<!ATTLIST param value CDATA #REQUIRED>
<!ATTLIST param name CDATA #IMPLIED>

<!ELEMENT description ()>

<!--
	component extension describes common attributes with additional meta information
	for component attributes in case these attributes are present in other types of tag libs.
	For example this element could add proposals for every "rendered" attributes for any tag lib.
-->
<!ELEMENT component-extension (attribute*) >

=== jbosstools/jbosstools-jst/plugins/org.jboss.tools.jst.web.kb/taglibs/Ajax4jsf.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE tag-lib PUBLIC "-//Red Hat, Inc//DTD Knowledge Base 2.0//EN" "http://anonsvn.jboss.org/repos/jbosstools/trunk/jst/plugins/org.jboss.tools.jst.web.kb/resources/kbCustomTagLibSchema-1.0.dtd">
<tag-lib defaultPrefix="a4j">
	<customExtension>
		<attribute name="ajaxSingle">
			<proposal type="enumeration">
				<param value="true" />
				<param value="false" />
			</proposal>
		</attribute>
		<attribute name="bypassUpdates">
			<proposal type="enumeration">
				<param value="true" />
				<param value="false" />
			</proposal>
		</attribute>
		<attribute name="ignoreDupResponses">
			<proposal type="enumeration">
				<param value="true" />
				<param value="false" />
			</proposal>
		</attribute>
		<attribute name="limitToList">
			<proposal type="enumeration">
				<param value="true" />
				<param value="false" />
			</proposal>
		</attribute>
		<attribute name="selfRendered">
			<proposal type="enumeration">
				<param value="true" />
				<param value="false" />
			</proposal>
		</attribute>
		<attribute name="ajaxRendered">
			<proposal type="enumeration">
				<param value="true" />
				<param value="false" />
			</proposal>
		</attribute>
	</customExtension>

	<component closeTag="true" name="loadBundle">
        <attribute name="basename">
            <proposal type="bundleName"/>
        </attribute>
	</component>

	<component name="actionparam">
		<attribute name="noEscape">
			<proposal type="enumeration">
				<param value="true" />
				<param value="false" />
			</proposal>
		</attribute>
	</component>
	<component name="commandButton">
		<attribute name="image">
			<proposal type="file">
				<param name="extensions" value="%image%" />
				<param name="pathType" value="absolute" />
				<param name="pathAddition"
					value="#{facesContext.externalContext.requestContextPath}" />
			</proposal>
		</attribute>
	</component>
	<component name="commandLink">
		<attribute name="shape">
			<proposal type="enumeration">
				<param value="default" />
				<param value="rect" />
				<param value="circle" />
				<param value="poly" />
			</proposal>
		</attribute>
		<attribute name="value" required="true" />
	</component>
	<component body-content="allowed" name="form">
		<attribute name="ajaxSubmit">
			<proposal type="enumeration">
				<param value="true" />
				<param value="false" />
			</proposal>
		</attribute>
	</component>
	<component body-content="allowed" name="htmlCommandLink">
		<attribute name="shape">
			<proposal type="enumeration">
				<param value="default" />
				<param value="rect" />
				<param value="circle" />
				<param value="poly" />
			</proposal>
		</attribute>
	</component>
	<component name="include">
		<attribute name="keepTransient">
			<proposal type="enumeration">
				<param value="true" />
				<param value="false" />
			</proposal>
		</attribute>
		<attribute name="layout">
			<proposal type="enumeration">
				<param value="block" />
				<param value="inline" />
				<param value="none" />
			</proposal>
		</attribute>
	</component>
	<component name="keepAlive">
		<attribute name="ajaxOnly">
			<proposal type="enumeration">
				<param value="true" />
				<param value="false" />
			</proposal>
		</attribute>
	</component>
	<component name="loadStyle">
		<attribute name="media">
			<proposal type="enumeration">
				<param value="all" />
				<param value="screen" />
				<param value="print" />
				<param value="projection" />
				<param value="braille" />
				<param value="speech" />
			</proposal>
		</attribute>
		<attribute name="src" required="true" />
	</component>
	<component name="log">
		<attribute name="level">
			<proposal type="enumeration">
				<param value="FATAL" />
				<param value="ERROR" />
				<param value="WARN" />
				<param value="INFO" />
				<param value="DEBUG" />
				<param value="ALL" />
			</proposal>
		</attribute>
	</component>
	<component name="mediaOutput">
		<attribute name="align">
			<proposal type="enumeration">
				<param value="bottom" />
				<param value="middle" />
				<param value="top" />
			</proposal>
		</attribute>
		<attribute name="cacheable">
			<proposal type="enumeration">
				<param value="true" />
				<param value="false" />
			</proposal>
		</attribute>
		<attribute name="session">
			<proposal type="enumeration">
				<param value="true" />
				<param value="false" />
			</proposal>
		</attribute>
		<attribute name="shape">
			<proposal type="enumeration">
				<param value="default" />
				<param value="rect" />
				<param value="circle" />
				<param value="poly" />
			</proposal>
		</attribute>
	</component>
	<component body-content="allowed" name="outputPanel">
		<attribute name="keepTransient">
			<proposal type="enumeration">
				<param value="true" />
				<param value="false" />
			</proposal>
		</attribute>
		<attribute name="layout">
			<proposal type="enumeration">
				<param value="block" />
				<param value="inline" />
				<param value="none" />
			</proposal>
		</attribute>
	</component>
	<component name="queue">
		<attribute name="sizeExceededBehavior">
			<proposal type="enumeration">
				<param value="dropNext" />
				<param value="dropNew" />
				<param value="fireNext" />
				<param value="fireNew" />
			</proposal>
		</attribute>
	</component>
	<component body-content="allowed" name="region">
		<attribute name="renderRegionOnly">
			<proposal type="enumeration">
				<param value="true" />
				<param value="false" />
			</proposal>
		</attribute>
	</component>
	<component body-content="allowed" name="status">
		<attribute name="forceId">
			<proposal type="enumeration">
				<param value="true" />
				<param value="false" />
			</proposal>
		</attribute>
		<attribute name="layout">
			<proposal type="enumeration">
				<param value="block" />
				<param value="inline" />
			</proposal>
		</attribute>
	</component>
</tag-lib>

=== jbosstools/jbosstools-jst/plugins/org.jboss.tools.jst.web.kb/taglibs/Facelets.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE tag-lib PUBLIC "-//Red Hat, Inc//DTD Knowledge Base 2.0//EN" "http://anonsvn.jboss.org/repos/jbosstools/trunk/jst/plugins/org.jboss.tools.jst.web.kb/resources/kbCustomTagLibSchema-1.0.dtd">
<tag-lib defaultPrefix="ui">
	<component name="component" extended="false">
		<description>The component tag and the composition tag behave exactly
			the same, except the component tag will insert a new UIComponent
			instance into the tree as the root of all the child
			components/fragments it has.</description>
		<attribute extended="false" name="id">
			<description>A unique id may be provided, otherwise Facelets will
				automatically assign one under the same logic it uses for all
				UIComponents.</description>
		</attribute>
		<attribute extended="false" name="binding">
			<description>This binding attribute is used the same as with any
				other UIComponent such that it allows you to reference them as a
				property of a JavaBean. If that target property did not have a
				UIComponent instance assigned already, JavaServer Faces will lazily
				create an instance for you and set it on your JavaBean before
				continuing with building the tree.</description>
		</attribute>
	</component>
	<component name="composition" extended="false">
		<attribute extended="false" name="template">
			<description>The resolvable URI of the template to use. The content
				within the composition tag will be used in populating the template
				specified.</description>
			<proposal type="file">
				<param name="extensions" value="%page%" />
			</proposal>
		</attribute>
	</component>
	<component closeTag="true" name="debug" extended="false">
		<description>The debug tag will capture the component tree and
			variables when it is encoded, storing the data for retrieval later.
			You may launch the debug window at any time from your browser by
			pressing 'CTRL' + 'SHIFT' + 'D' (by default). The debug tag doesn't
			need to be used with the facelet.DEVELOPMENT parameter. The best
			place to put this tag is in your site's main template where it can be
			enabled/disabled across your whole application. If your application
			uses multiple windows, you might want to assign different hot keys to
			each one.</description>
		<attribute extended="false" name="hotkey">
			<description>The hot key to use in combination with 'CTRL' + 'SHIFT'
				to launch the debug window. By default, when the debug tag is used,
				you may launch the debug window with 'CTRL' + 'SHIFT' + 'D'. This
				value cannot be an EL expression.</description>
		</attribute>
		<attribute extended="false" name="rendered">
			<description>Creating debug output on every request adds some
				overhead, so you can use the UIComponent rendered property to turn
				debugging on or off based on some expression.</description>
			<proposal type="enumeration">
				<param value="true" />
				<param value="false" />
			</proposal>
		</attribute>
	</component>
	<component name="decorate" extended="false">
		<description>The decorate tag acts the same as a composition tag, but
			it will not trim everything outside of it. This is useful in cases
			where you have a list of items in a document, which you would like to
			be decorated or framed. The sum of it all is that you can take any
			element in the document and decorate it with some external logic as
			provided by the template.</description>
		<attribute extended="false" name="template" required="true">
			<description>The resolvable URI of the template to use. The content
				within the decorate tag will be used in populating the template
				specified.</description>
			<proposal type="file">
				<param name="extensions" value="%page%" />
			</proposal>
		</attribute>
	</component>
	<component name="define" extended="false">
		<description>The define tag can be used within tags that allow
			templating. This includes composition and decorate tags.</description>
		<attribute extended="false" name="name" required="true">
			<description>The literal name for this definition. This name will
				match up with a &lt;ui:insert/&gt; tag in a target template.</description>
		</attribute>
	</component>
	<component name="fragment" extended="false">
		<description>Just like composition has decorate as a non-trimming
			version of the same behavior, component has fragment. This allows you
			to logically insert a UIComponent into the tree and possibly bind
			this fragment to a JavaBean property or Map for management. The
			fragment tag was also added to Facelets to get around some of the
			optimizations used in handling text within your document. If you are
			using components such as &lt;f:panelGrid/&gt;, which renders its
			children, you may want more control over the building process that
			Facelets does and using a fragment tag will help guarantee
			parent/child relationships for you.</description>
		<attribute extended="false" name="id">
			<description>A unique id may be provided, otherwise Facelets will
				automatically assign one under the same logic it uses for all
				UIComponents.</description>
		</attribute>
		<attribute extended="false" name="binding">
			<description>This binding attribute is used the same as with any
				other UIComponent such that it allows you to reference them as a
				property of a JavaBean. If that target property did not have a
				UIComponent instance assigned already, JavaServer Faces will lazily
				create an instance for you and set it on your JavaBean before
				continuing with building the tree.</description>
		</attribute>
	</component>
	<component closeTag="true" name="include" extended="false">
		<description>The include tag can point at any Facelet which might use
			the composition tag, component tag, or simply be straight XHTML/XML.
			It should be noted that the src path does allow relative path names,
			but they will always be resolved against the original Facelet
			requested. The include tag can be used in conjunction with multiple
			&lt;ui:param/&gt; tags to pass EL expressions/values to the target
			page.</description>
		<attribute extended="false" name="src" required="true">
			<description>A literal or EL expression that specifies the target
				Facelet that you would like to include into your document.</description>
			<proposal type="file">
				<param name="extensions" value="%page%" />
			</proposal>
		</attribute>
	</component>
	<component name="insert" extended="false">
		<description>The insert tag is used within your templates to declare
			spots of replacable data.</description>
		<attribute extended="false" name="name">
			<description>The optional name attribute matches the associated
				&lt;ui:define/&gt; tag in this template's client. If no name is
				specified, it's expected that the whole template client will be
				inserted.</description>
		</attribute>
	</component>
	<component closeTag="true" name="param" extended="false">
		<description />
		<attribute extended="false" name="name" required="true">
			<description>The name of the variable to pass to the included
				Facelet.</description>
		</attribute>
		<attribute extended="false" name="value" required="true">
			<description>The literal or EL expression value to assign to the
				named variable.</description>
		</attribute>
	</component>
	<component name="remove" extended="false">
		<description>The remove tag does not have any attributes and is used
			to remove chunks of XML content from a Facelet at compilation time.
			The remove tag is often used in conjunction with the jsfc feature.</description>
	</component>
	<component name="repeat" extended="false">
		<attribute extended="false" name="value" required="true">
			<description>Expression for the list of items</description>
		</attribute>
		<attribute extended="false" name="var" required="true">
			<description>The name of the variable to put the current item.</description>
		</attribute>
		<attribute extended="false" name="offset">
			<description>The offset index.</description>
		</attribute>
		<attribute extended="false" name="size">
			<description>Number of items to produce.</description>
		</attribute>
		<attribute extended="false" name="varStatus">
			<description>Index object.</description>
		</attribute>
	</component>
</tag-lib>

=== jbosstools/jbosstools-jst/plugins/org.jboss.tools.jst.web.kb/taglibs/jQueryMobile.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE tag-lib PUBLIC "-//Red Hat, Inc//DTD Knowledge Base 2.0//EN" "http://anonsvn.jboss.org/repos/jbosstools/trunk/jst/plugins/org.jboss.tools.jst.web.kb/resources/kbCustomTagLibSchema-1.0.dtd">
<tag-lib defaultPrefix="jQueryMobile" ignoreCase="true">
	<component extended="false" name="a" attributeProvider="org.jboss.tools.jst.web.kb.internal.taglib.jq.PopupAnchorAttributeProvider, org.jboss.tools.jst.web.kb.internal.taglib.jq.AButtonAttributeProvider, org.jboss.tools.jst.web.kb.internal.taglib.jq.LinkAttributeProvider"/>
	<component extended="false" name="button" attributeProvider="org.jboss.tools.jst.web.kb.internal.taglib.jq.ButtonAttributeProvider"/>
	<component extended="false" name="input" attributeProvider="org.jboss.tools.jst.web.kb.internal.taglib.jq.TextInputAndTextareaAttributeProvider, org.jboss.tools.jst.web.kb.internal.taglib.jq.SliderAttributeProvider, org.jboss.tools.jst.web.kb.internal.taglib.jq.RadioButtonAttributeProvider, org.jboss.tools.jst.web.kb.internal.taglib.jq.ButtonAttributeProvider, org.jboss.tools.jst.web.kb.internal.taglib.jq.CheckboxAttributeProvider"/>
	<component extended="false" name="textarea" attributeProvider="org.jboss.tools.jst.web.kb.internal.taglib.jq.TextInputAndTextareaAttributeProvider"/>

	<component extended="false" name="div" attributeProvider="org.jboss.tools.jst.web.kb.internal.taglib.jq.ControlgroupAttributeProvider, org.jboss.tools.jst.web.kb.internal.taglib.jq.PopupAttributeProvider, org.jboss.tools.jst.web.kb.internal.taglib.jq.PageAttributeProvider, org.jboss.tools.jst.web.kb.internal.taglib.jq.PageAttributeProvider, org.jboss.tools.jst.web.kb.internal.taglib.jq.NavbarAttributeProvider, org.jboss.tools.jst.web.kb.internal.taglib.jq.FooterHeaderAttributeProvider, org.jboss.tools.jst.web.kb.internal.taglib.jq.FixedToolbarAttributeProvider, org.jboss.tools.jst.web.kb.internal.taglib.jq.FieldcontainAttributeProvider, org.jboss.tools.jst.web.kb.internal.taglib.jq.EnhancementAttributeProvider, org.jboss.tools.jst.web.kb.internal.taglib.jq.DialogAttributeProvider, org.jboss.tools.jst.web.kb.internal.taglib.jq.CollapsibleAttributeProvider, org.jboss.tools.jst.web.kb.internal.taglib.jq.CollapsibleSetAttributeProvider, org.jboss.tools.jst.web.kb.internal.taglib.jq.ContentAttributeProvider"/>
	<component extended="false" name="fieldset" attributeProvider="org.jboss.tools.jst.web.kb.internal.taglib.jq.ControlgroupAttributeProvider, org.jboss.tools.jst.web.kb.internal.taglib.jq.PopupAttributeProvider, org.jboss.tools.jst.web.kb.internal.taglib.jq.PageAttributeProvider, org.jboss.tools.jst.web.kb.internal.taglib.jq.PageAttributeProvider, org.jboss.tools.jst.web.kb.internal.taglib.jq.NavbarAttributeProvider, org.jboss.tools.jst.web.kb.internal.taglib.jq.FooterHeaderAttributeProvider, org.jboss.tools.jst.web.kb.internal.taglib.jq.FixedToolbarAttributeProvider, org.jboss.tools.jst.web.kb.internal.taglib.jq.FieldcontainAttributeProvider, org.jboss.tools.jst.web.kb.internal.taglib.jq.EnhancementAttributeProvider, org.jboss.tools.jst.web.kb.internal.taglib.jq.DialogAttributeProvider, org.jboss.tools.jst.web.kb.internal.taglib.jq.CollapsibleAttributeProvider, org.jboss.tools.jst.web.kb.internal.taglib.jq.CollapsibleSetAttributeProvider, org.jboss.tools.jst.web.kb.internal.taglib.jq.ContentAttributeProvider"/>

	<component extended="false" name="span" attributeProvider="org.jboss.tools.jst.web.kb.internal.taglib.jq.PopupAttributeProvider, org.jboss.tools.jst.web.kb.internal.taglib.jq.PageAttributeProvider, org.jboss.tools.jst.web.kb.internal.taglib.jq.PageAttributeProvider, org.jboss.tools.jst.web.kb.internal.taglib.jq.NavbarAttributeProvider, org.jboss.tools.jst.web.kb.internal.taglib.jq.FooterHeaderAttributeProvider, org.jboss.tools.jst.web.kb.internal.taglib.jq.FixedToolbarAttributeProvider, org.jboss.tools.jst.web.kb.internal.taglib.jq.FieldcontainAttributeProvider, org.jboss.tools.jst.web.kb.internal.taglib.jq.EnhancementAttributeProvider, org.jboss.tools.jst.web.kb.internal.taglib.jq.DialogAttributeProvider, org.jboss.tools.jst.web.kb.internal.taglib.jq.CollapsibleAttributeProvider, org.jboss.tools.jst.web.kb.internal.taglib.jq.CollapsibleSetAttributeProvider, org.jboss.tools.jst.web.kb.internal.taglib.jq.ContentAttributeProvider"/>

	<component extended="false" name="select" attributeProvider="org.jboss.tools.jst.web.kb.internal.taglib.jq.SelectAttributeProvider, org.jboss.tools.jst.web.kb.internal.taglib.jq.FlipToggleSwitchAttributeProvider"/>

	<component extended="false" name="ol" attributeProvider="org.jboss.tools.jst.web.kb.internal.taglib.jq.ListViewAttributeProvider"/>
	<component extended="false" name="ul" attributeProvider="org.jboss.tools.jst.web.kb.internal.taglib.jq.ListViewAttributeProvider"/>
	<component extended="false" name="li" attributeProvider="org.jboss.tools.jst.web.kb.internal.taglib.jq.ListviewItemAttributeProvider"/>

	<component extended="false" name="table" attributeProvider="org.jboss.tools.jst.web.kb.internal.taglib.jq.TableAttributeProvider"/>
	<component extended="false" name="th" attributeProvider="org.jboss.tools.jst.web.kb.internal.taglib.jq.ThAttributeProvider"/>
</tag-lib>

=== jbosstools/jbosstools-jst/plugins/org.jboss.tools.jst.web.kb/taglibs/Html.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE tag-lib PUBLIC "-//Red Hat, Inc//DTD Knowledge Base 2.0//EN" "http://anonsvn.jboss.org/repos/jbosstools/trunk/jst/plugins/org.jboss.tools.jst.web.kb/resources/kbCustomTagLibSchema-1.0.dtd">
<tag-lib defaultPrefix="htmlFile" ignoreCase="true">
	<component extended="false" name="script" attributeProvider="org.jboss.tools.jst.web.kb.internal.taglib.html.ScriptAttributeProvider"/>
	<component extended="false" name="link" attributeProvider="org.jboss.tools.jst.web.kb.internal.taglib.html.LinkAttributeProvider"/>
	<component extended="false" name="img" attributeProvider="org.jboss.tools.jst.web.kb.internal.taglib.html.ImageAttributeProvider"/>
	<component extended="false" name="video" attributeProvider="org.jboss.tools.jst.web.kb.internal.taglib.html.VideoAttributeProvider"/>
	<component extended="false" name="audio" attributeProvider="org.jboss.tools.jst.web.kb.internal.taglib.html.AudioAttributeProvider"/>
	<component extended="false" name="source" attributeProvider="org.jboss.tools.jst.web.kb.internal.taglib.html.VideoAttributeProvider, org.jboss.tools.jst.web.kb.internal.taglib.html.AudioAttributeProvider"/>
	<component extended="false" name="a" attributeProvider="org.jboss.tools.jst.web.kb.internal.taglib.html.AAttributeProvider"/>
</tag-lib>
